server:
  port: 8761
spring:
  config:
    import: configserver:http://localhost:8888

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true
