

server:
  port: 8888

spring:
  application:
    name: configServer
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config, file:./config

    compatibility-verifier:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


