spring:
  application:
    name: userManagement
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: password
server:
  port: 8082

kafka:
  bootstrap-servers: localhost:9092
  topic: user-topic
